# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdfupload',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
